### PR TITLE
configurable availability zones.

### PR DESCRIPTION
**Pull request by hjhart**
This solution worked for me – fixes  https://github.com/pivotal/lobot/issues/63

### CODE REVIEW

**Comment by kmayer** [comment]
It's a solution to the immediate problem, so possibly +1. On the other hand, this pushes the responsibility to the person configuring lobot. 

I'd prefer a default behavior that "does the right thing" for 85% of the cases, but can be overridden. The conflict is between choosing any A.Z. and reserving instances in just one.

**Comment by pivotalrp** [comment]
> I'd prefer a default behavior that "does the right thing" for 85% of the cases, but can be overridden. 

I think this is what the code in the pull request does? ~ @hiremaga

@hjhart is working on a fix for the build, he'll resubmit this pull request shortly.

**Comment by hjhart** [comment]
Build is now fixed and is now part of the pull request

**Comment by kmayer** [comment]
Okay, I think this is the simplest thing that can possibly work. We'll merge it in. I have another story in the backlog for an algorithmic choice of an az.

**Comment by pivotalcommon** [comment]
We are in the process of transitioning this gem to its new name: ciborg. We have merged this pull request into the new ciborg repository:

https://github.com/pivotal/ciborg/commit/bf90e95d1933bfdc8092637e50caaf7b2b0919e5

Please submit all future pull requests to the new repository.

Thanks!
George and Laura

**Pull request closed without merging**
