### PR TITLE
Uncomment ci:headlessly rake task

### PR DESCRIPTION
**Pull request by BrentWheeldon**
If this rake task isn't the way to do headless testing anymore let me know and I'll change the pull request to add some documentation to the gem about it.

### CODE REVIEW

**Comment by mkocher** [comment]
Have you been using HEAD or the prerelease version of the gem?  The last released version should have headless as a task.

Lobot is undergoing some major transformations if you look at the recent commits.  We're moving to Ubuntu, and moving all of the rake tasks and cap tasks into one `lobot` command.  The more exciting change is we're moving to using the Travis-CI cookbooks for configuring the CI environment.  All of this stuff is _close_ to landing but not quite ready.  The prerelease gem should work and get you everything except the consolidated lobot command if you want to try it out.

That being said, with the next release we were planning on killing the headless support, and trying out the [jenkins xvfb plugin](https://wiki.jenkins-ci.org/display/JENKINS/Xvfb+Plugin).  We figure we can always add the headless support back in, but a major version bump is a good time to take it away.  The rake ci:headlessly was convenient, but it slows down the build as it loads up the rake environment just to shell out, usually to rake.

**Comment by BrentWheeldon** [comment]
We were using HEAD because TeamCity doesn't work in the currently released version (fixed in this [pull request](https://github.com/pivotal/lobot/pull/20), just not released). We'll lock to an old SHA for now and deal with the upgrade when that happens.

**Comment by mkocher** [comment]
Hmm, does Team City have anything for xvfb support like Jenkins?  I haven't ever used the team city support, but the recipe seems tor really need an overhaul.

**Comment by BrentWheeldon** [comment]
Not too sure. There's every chance we'll move to Jenkins soon anyway, so it
probably won't be an issue for us.

**Pull request closed without merging**
