### PR TITLE
Install fonts for jenkins graphs

### PR DESCRIPTION
**Pull request by slackersoft**

### CODE REVIEW

**Comment by mkocher** [comment]
Any reason not to use package resources instead of shelling out to yum?

**Comment by slackersoft** [comment]
I just grabbed what we did on the CI machine as we were trying to solve the problem. And it looked like other recipes were also shelling out to yum, so it seemed reasonable. Potentially, more testing could be done about which actual font packages fixed the problem, but we were tired of fighting it, so we just installed everything in the list we were looking at.

**Comment by mkocher** [comment]
This didn't make it into the last release as we had to get it out to fix a timing bug that was cropping up more and more.  I'm certainly planning on merging it as soon as I can test it out.

**Comment by pivotalcommon** [comment]
Since the pull request can't be automatically merged I went ahead and squashed the 2 commits into 1 and it is now on master.

https://github.com/pivotal/lobot/commit/89bd53d51ec19ccdc1a77fad7b42258ab9661736

**Pull request closed without merging**
